name: CI

on:
  push:
    branches:
      - template

jobs:
  render:
    runs-on: ubuntu-latest 
    name: Render template
    steps:
    - name: 'Checkout the source code from GitHub'
      uses: actions/checkout@v2
    - name: Create dist/ directory
      run: mkdir -p ./dist
    - name: Install dependencies
      run: npm ci
    - name: Render README.md
      run: node ./tools/index.js
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Copy img/ directory
      run: cp -r ./img ./dist/img
    - name: Copy CONTRIBUTING
      run: cp -r ./CONTRIBUTING ./dist/CONTRIBUTING
    - name: Deploy
      if: ${{ github.ref == 'refs/heads/template' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./dist
        enable_jekyll: true